FROM python:3
WORKDIR /usr/src/app
RUN apt-get update 
RUN apt-get install ffmpeg libsm6 libxext6 -y
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY web web

ENV PORT=5000

RUN useradd -m myuser
USER myuser
CMD gunicorn web.app:app --bind 0.0.0.0:$PORT --reload